cocoindex-io/cocoindex

src/ops/storages/postgres.rs

pgvector is using cosine *distance* and *negative* inner product, so we need a conversion.

Correct similarity score for cosine / inner product.

---

README.md

Add quickstart video tutorial to the readme

Add quickstart video tutorial to the readme

---

.github/workflows/docs.yml

(it's only testable after merging to main)

Further fix docs deployment workflow.

---

src/ops/functions/split_recursively.rs

Skip chunks without alphanumeric characters.

---

src/base/json_schema.rs
src/base/schema.rs
src/base/spec.rs
src/base/value.rs
src/builder/analyzed_flow.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/execution/db_tracking.rs
src/execution/db_tracking_setup.rs
src/execution/evaluator.rs
src/execution/indexer.rs
src/execution/memoization.rs
src/llm/ollama.rs
src/llm/openai.rs
src/ops/factory_bases.rs
src/ops/functions/split_recursively.rs
src/ops/registry.rs
src/ops/sources/google_drive.rs
src/ops/sources/local_file.rs
src/ops/storages/postgres.rs
src/service/error.rs
src/service/flows.rs
src/service/search.rs
src/setup/db_metadata.rs
src/setup/driver.rs
src/setup/states.rs
src/utils/db.rs
src/utils/fingerprint.rs

This PR applies a bunch a bunch of Clippy fixes I found when working with the project. No change in behaviour.

chore: Clippy fixes

---

src/execution/indexer.rs
src/service/flows.rs

Code cleanup / refactor to prepare for evaluation feature

---

src/execution/db_tracking.rs
src/execution/row_indexer.rs
src/execution/source_indexer.rs
src/execution/stats.rs
src/ops/sdk.rs
src/prelude.rs
src/py/mod.rs
src/service/flows.rs

Update `indexer` to keep key states in memory for continuous processing

---

examples/gdrive_text_embedding/main.py
python/cocoindex/__init__.py
python/cocoindex/flow.py

Simplify refresh options argument for `FlowBuilder.add_source`.

---

examples/docs_to_kg/main.py
python/cocoindex/storages.py
src/ops/storages/neo4j.rs

Support extra properties for nodes in knowledge graph.

---

README.md

Preview link - https://github.com/cocoindex-dev/cocoindex

Update badges - add documentation and pypi status

---

README.md

docs: Listed the Qdrant example in README.md

---

README.md
examples/fastapi_server_docker/.dockerignore
examples/fastapi_server_docker/.env
examples/fastapi_server_docker/README.md
examples/fastapi_server_docker/compose.yaml
examples/fastapi_server_docker/dockerfile
examples/fastapi_server_docker/main.py
examples/fastapi_server_docker/requirements.txt
examples/fastapi_server_docker/sample_code/main.py
examples/fastapi_server_docker/src/cocoindex_funs.py

This example contains a simple docker compose which runs pg17 along with a simple fastapi endpoint for querying on code.

Added new fastapi_server_docker example

---

Cargo.toml

chore(release): enable lto for release

---

src/execution/dumper.rs
src/execution/row_indexer.rs
src/execution/source_indexer.rs
src/ops/interface.rs
src/ops/sources/google_drive.rs
src/ops/sources/local_file.rs
src/service/flows.rs

feat: make source get API return ordinal optionally

---

docs/docs/core/basics.md
docs/docs/core/flow_def.mdx
docs/docs/getting_started/quickstart.md
docs/docs/query.mdx
docs/sidebars.ts

docs(query): add docs for CocoIndex query support

---

examples/text_embedding/Text_Embedding.ipynb

Relates to #515, #518.
The query handler logic has been changed since those PRs, but it seems the code part in the Jupyter Notebook has never been changed (#530 updates the CLI part, but not query logic).
P.S. It appears that my editor rearranges the metadata a lot when I modify the notebook code.

Update jupyter notebook code in text embedding example

---

python/cocoindex/functions.py
src/ops/functions/split_recursively.rs
src/ops/registration.rs

feat(chunking): allow customizing separators for the splitter

---

docs/docs/ops/functions.md
src/ops/functions/split_recursively.rs

feat(split): add line/column to output of SplitRecursively

---

docs/docs/core/flow_def.mdx
docs/docs/core/settings.mdx
python/cocoindex/setting.py
src/base/spec.rs
src/builder/analyzer.rs
src/builder/plan.rs
src/execution/source_indexer.rs
src/lib_context.rs
src/settings.rs
src/utils/concur_control.rs

feat(global-concur-control): provide a global controller

---

python/cocoindex/op.py

Only when a basic type / any type is annotated, we decode the primary key columns to a single value instead of a struct.
This means they can always explicitly create a struct type (namedtuple or dataclass) if they want even when there's only a single primary key column. This will allow users to handle multiple-primary-key-columns in a consistent way.

chore: restrict the cond of decoding key to basic types for mutations

---

src/base/spec.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs

fix(data-slice): make data slice types reflect newly added fields

---

docs/docs/core/flow_methods.mdx
docs/docs/tutorials/manage_flow_dynamically.mdx
docs/sidebars.ts

docs: tutorial for dynamically managed flows

---

README.md

Use pepy.tech badge 
https://pepy.tech/projects/cocoindex
pypistats is down

Update README.md - Use badge from pepy.tech, pypistats is down

---

Cargo.lock
Cargo.toml
docs/docs/ops/functions.md
src/ops/functions/split_recursively.rs

feat(tree-sitter-solidity): support Solidity in `SplitRecursively`

---

.github/SECURITY.md

Updated the SECURITY.md file to clarify reporting policies and response times.

Revise security reporting guidelines in SECURITY.md

---

src/ops/targets/postgres.rs

feat(postgres-sql-attachments): allow multiple statements executed

---

src/ops/functions/split_recursively.rs
src/ops/shared/mod.rs
src/ops/shared/program_langs.rs

refactor: extract the language list into a separate mod

---

Cargo.lock
Cargo.toml
docs/docs/targets/postgres.md
python/cocoindex/targets/_engine_builtin_specs.py
src/ops/targets/postgres.rs

feat(halfvec): support `halfvec` for postgres target
