python/cocoindex/setup.py
python/cocoindex/typing.py

Bunch of serialization fixes in Python SDK

---

src/ops/py_factory.rs

Previously we're using the `Serialize` so bytes become base64 strings

Use custom code to convert Rust values to Python so bytes are bytes

---

.github/workflows/docs.yml

This is to avoid a forked repo triggering this job which is deemed to fail.

Trigger the docs `deploy` job only when `GH_PAGES_DEPLOY` secret is set.

---

examples/manual_extraction/manual_extraction.py

Doesn't work yet - engine side needs some debug.

Switch to the `ExtractByMistral` in the `manual_extraction` example. #27 

---

docs/docs/about/contributing.md

. .env.lib_debug don't work for my shell which is zsh. ptal
https://cocoindex.io/docs/about/contributing

Make the step of set extra environment variables work for both zsh and bash

---

Cargo.toml
src/ops/functions/split_recursively.rs

Add per-language information and terminate at "inline" for Markdown.

---

Cargo.toml
python/cocoindex/sources.py
src/ops/registration.rs
src/ops/sources/google_drive.rs
src/ops/sources/mod.rs

Partial implementation for Google Drive source - list

---

docs/docs/ops/sources.md

Add documentation for the `GoogleDrive` source.

---

src/base/value.rs
src/ops/sources/google_drive.rs

Add a field `mime_type` for `GoogleDrive` source.

---

README.md
examples/gdrive_text_embedding/.env.example
examples/gdrive_text_embedding/README.md

Update `README.md` files for the `gdrive_text_embedding` example.

---

Cargo.toml
python/cocoindex/cli.py
python/cocoindex/flow.py
src/base/value.rs
src/builder/plan.rs
src/execution/dumper.rs
src/execution/indexer.rs
src/execution/mod.rs
src/py/mod.rs
src/service/flows.rs

Implement `evaluate_and_dump` and provide a `evaluate` subcommand for it

---

docs/docs/core/cli.mdx
docs/docs/core/flow_methods.mdx
python/cocoindex/__init__.py
python/cocoindex/cli.py
python/cocoindex/flow.py

Update documentations for the evaluation and dump functionality

---

Cargo.toml
src/base/json_schema.rs
src/base/schema.rs
src/base/value.rs
src/execution/query.rs
src/ops/storages/postgres.rs

Add uuid type support in core engine.

---

docs/docs/core/data_types.mdx
python/cocoindex/convert.py
python/cocoindex/typing.py
src/py/convert.rs

Support `Uuid` type in core engine / Python value binding.

---

Cargo.toml
src/base/schema.rs
src/base/spec.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/builder/plan.rs
src/execution/db_tracking.rs
src/execution/dumper.rs
src/execution/evaluator.rs
src/execution/indexer.rs
src/execution/memoization.rs
src/execution/mod.rs
src/service/flows.rs
src/utils/fingerprint.rs

Rust core support for generating stable automatic UUID in collector

---

src/base/json_schema.rs
src/llm/mod.rs
src/llm/openai.rs
src/ops/functions/extract_by_llm.rs

We use union type (with `null`) to mark fields optional.
Background:
https://platform.openai.com/docs/guides/structured-outputs/supported-schemas#all-fields-must-be-required

For OpenAI, make all fields required in JSON schema.

---

Cargo.toml
python/cocoindex/typing.py
src/base/json_schema.rs
src/base/schema.rs
src/base/value.rs
src/execution/query.rs
src/llm/mod.rs
src/llm/openai.rs
src/ops/storages/postgres.rs
src/py/convert.rs

Support date/time types

---

docs/docs/core/data_types.mdx

Add documents for date/time types.

---

src/base/json_schema.rs
src/base/value.rs
src/llm/mod.rs
src/llm/ollama.rs
src/llm/openai.rs
src/ops/functions/extract_by_llm.rs

Output field descriptions as extra output for ollama which doesn't really support description

---

src/base/schema.rs
src/builder/analyzer.rs
src/builder/plan.rs
src/execution/indexer.rs

Avoid compute/store another fp on content if uuid is already the key.

---

Cargo.toml
src/execution/evaluator.rs
src/execution/indexer.rs
src/lib.rs
src/ops/interface.rs
src/ops/sdk.rs
src/ops/sources/google_drive.rs
src/ops/sources/local_file.rs
src/prelude.rs

Incremental processing: propagate ordinal from source and skip processing a row if ordinal+logic has no change

---

Cargo.toml
src/execution/dumper.rs
src/execution/indexer.rs
src/ops/interface.rs
src/ops/sources/google_drive.rs
src/ops/sources/local_file.rs
src/prelude.rs
src/service/flows.rs

Change source's `list()` API to streaming and return ordinal.

---

src/base/spec.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/builder/plan.rs
src/execution/dumper.rs
src/execution/evaluator.rs
src/execution/row_indexer.rs
src/execution/source_indexer.rs
src/lib_context.rs
src/service/flows.rs

Change `source_op` to `import_op` and add a `ImportOpSpec` layer.

---

src/base/spec.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/builder/plan.rs
src/execution/mod.rs
src/execution/source_indexer.rs
src/execution/synchronizer.rs
src/py/mod.rs
src/service/flows.rs

Support periodically refresh by `Synchrnoizer`

---

Cargo.toml
python/cocoindex/cli.py
python/cocoindex/flow.py
src/execution/memoization.rs
src/lib_context.rs
src/py/mod.rs

Expose `update()` and `FlowSynchronizer::join()` as async Python functions

---

examples/gdrive_text_embedding/main.py
python/cocoindex/__init__.py
python/cocoindex/flow.py

Python SDK exposes `refresh_options` for `add_source`.

---

src/execution/live_updater.rs
src/execution/source_indexer.rs
src/execution/stats.rs
src/ops/interface.rs

Engine supports dispatching change stream coming from source.

---

examples/gdrive_text_embedding/main.py
python/cocoindex/__init__.py
python/cocoindex/flow.py
src/execution/live_updater.rs

Change gdrive example to continously watch change in main.

---

examples/gdrive_text_embedding/README.md

Update `README.md` for the GDrive example for live update capability.

---

docs/docs/core/basics.md
docs/docs/core/flow_def.mdx
docs/docs/core/flow_methods.mdx
docs/docs/ops/sources.md

Update docs for incremental update supports.

---

python/cocoindex/cli.py
python/cocoindex/setup.py
src/builder/flow_builder.rs
src/lib_context.rs
src/py/mod.rs
src/setup/driver.rs

- Explicit support for setup deletions, no matter if present in the current process.
- Clearly show persisted setup in `ls` even if not in the current process.

Make setup management more flexible and straightforward.

---

Cargo.toml
dev/neo4j.yaml
src/ops/storages/mod.rs
src/ops/storages/neo4j.rs

Implement target index for Neo4j: without setup yet.

---

src/builder/analyzed_flow.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/ops/factory_bases.rs
src/ops/interface.rs
src/ops/registration.rs
src/ops/storages/neo4j.rs
src/ops/storages/postgres.rs
src/prelude.rs
src/py/mod.rs
src/setup/driver.rs
src/setup/states.rs

Add setup logic for Neo4j target.

---

docs/docs/ops/storages.md
src/execution/live_updater.rs
src/execution/memoization.rs
src/execution/row_indexer.rs
src/execution/source_indexer.rs
src/ops/interface.rs
src/ops/sdk.rs
src/ops/sources/google_drive.rs
src/ops/sources/local_file.rs
src/ops/storages/neo4j.rs
src/ops/storages/postgres.rs
src/setup/auth_registry.rs
src/setup/states.rs
src/utils/retriable.rs

As the title goes.
Doesn't include fixes for `warning: very complex type used. Consider factoring parts into `type` definitions`.

chore: Some Clippy fixes

---

src/base/value.rs
src/ops/storages/neo4j.rs
src/ops/storages/postgres.rs
src/py/convert.rs

Implements https://github.com/cocoindex-io/cocoindex/issues/317
This PR migrates all usages of `Arc<[u8]>` to `bytes::Bytes` for bytes representation.

Refactor: migrate from Arc<[u8]> to bytes::Bytes

---

python/cocoindex/tests/test_convert.py

Implements https://github.com/cocoindex-io/cocoindex/issues/185

Add unit tests for Engine to Python format conversion

---

docs/docs/ai/llm.mdx
examples/manuals_llm_extraction/main.py
python/cocoindex/llm.py
src/lib_context.rs
src/llm/gemini.rs
src/llm/mod.rs

This PR adds native Gemini support in DataFlow, implementing [#350](https://github.com/cocoindex-io/cocoindex/issues/350).
**Summary of changes:**
- Added Gemini client and integration.
- Updated example and documentation to include Gemini usage.
- No breaking changes.
**Other changes:**
- Minor logger handling improvement in `lib_context.rs` (unrelated).

Feat: Add Gemini Support to DataFlow (Rust)

---

src/setup/states.rs

Fixes https://github.com/cocoindex-io/cocoindex/issues/369
Remove color from description in cli so that it uses the foreground color of the terminal, making it visible regardless of the theme.

Fix Title Visibility for bright backgrounds

---

examples/text_embedding/README.md

README of text embedding example now points to https://colab.research.google.com/github/cocoindex-io/cocoindex/blob/main/examples/text_embedding/Text_Embedding.ipynb

Update Colab Link to Match Github

---

python/cocoindex/query.py
src/ops/interface.rs
src/py/mod.rs
src/service/search.rs

feat(search): change search API result to inline key with values

---

python/cocoindex/lib.py
src/base/spec.rs
src/execution/db_tracking_setup.rs
src/lib_context.rs
src/ops/factory_bases.rs
src/ops/interface.rs
src/ops/registration.rs
src/ops/storages/postgres.rs
src/py/mod.rs
src/service/flows.rs
src/settings.rs
src/setup/db_metadata.rs
src/setup/driver.rs

feat(db): allow user/password to be configured separately for postgres

---

docs/docs/core/initialization.mdx

docs(supabase): provide info for connecting to Supabase postgres

---

src/ops/functions/split_recursively.rs

Adds unit tests covering basic functionality, overlap, whitespace trimming,
and discarding empty chunks for the SplitRecursively function.
Includes TODOs noting potential inconsistencies observed during testing
regarding overlap and whitespace handling for further investigation.
Closes #34

feat: Add unit tests for SplitRecursively function

---

Cargo.lock
docs/docs/core/basics.md
docs/docs/core/custom_function.mdx
docs/docs/core/data_types.mdx
docs/docs/core/flow_def.mdx
docs/docs/getting_started/quickstart.md
docs/docs/ops/functions.md
docs/docs/ops/sources.md
examples/manuals_llm_extraction/main.py
python/cocoindex/__init__.py
python/cocoindex/convert.py
python/cocoindex/flow.py
python/cocoindex/functions.py
python/cocoindex/op.py
python/cocoindex/tests/test_convert.py
python/cocoindex/typing.py
src/base/json_schema.rs
src/base/schema.rs
src/base/spec.rs
src/base/value.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/execution/evaluator.rs
src/ops/functions/split_recursively.rs
src/ops/sdk.rs
src/ops/sources/google_drive.rs
src/ops/sources/local_file.rs
src/ops/storages/neo4j.rs
src/py/convert.rs
src/service/flows.rs

feat(types): simplify/clarify data types (KTable, LTable, Vector, remove `.typing.`)

---

pyproject.toml
python/cocoindex/cli.py
python/cocoindex/flow.py

As the title states, this PR creates a helper method to make the output spec info more structured in a way that users can appreciate, and also modifies the show command to use colorful output mode by default.
Resolves #324
before:
```
{
"name": "TextEmbedding",
"import_ops": [
{...}
],
"reactive_ops": [
{...}
],
"export_ops": [
{...}
]
}
```
after:
\

feat: beautify show cli command with colorful structured output

---

python/cocoindex/cli.py

This PR will make `cocoindex ls` command way more efficient than before, and fix #412.
In the previous versions, we tried to access each Flow’s name property in the list comprehension:
```py
current_flow_names = [fl.name for fl in flow.flows()]
```
The name property of a Flow is defined as:
```py
@property
def name(self) -> str:
return self._lazy_engine_flow().name()
```
Each call to `self._lazy_engine_flow()` triggers the creation of the underlying `_engine.Flow` if it hasn’t been built yet. Till now, you can see we have done a lot of unnecessary jobs here, since only we need here is to retrieve flow names.
We use the helper now to quickly get flow names as a list.
```py
def flow_names() -> list[str]:
"""
Get the names of all flows.
"""
with _flows_lock:
return list(_flows.keys())
``` …

fix: make flow name retrieval efficient

---

python/cocoindex/auth_registry.py
python/cocoindex/storages.py

This PR updates `AuthEntryReference` to be generic (`AuthEntryReference[T]`) and also applies typed references to other specs.
Closes #393.

feat: make `AuthEntryReference` typed

---

python/cocoindex/cli.py
python/cocoindex/flow.py
src/py/mod.rs

This PR tries to resolve #411.
We implement a flow schema function on Rust side, and expose it to Python, so the `show` command can directly use. Aside, we use `rich.Table` to beautify the schema information of each flow.
Now, when using `cocoindex show`, aside from spec info, schema info will also print out at last as follows:

feat(cli): enhance flow display with schema rendering support

---

python/cocoindex/setting.py
src/server.rs

feat(port): use `localhost:9876/cocoindex` as default prefix

---

src/utils/yaml_ser.rs

Previously, in our implementations of yaml serialization, the `serialize_tuple_variant` and `serialize_struct_variant` methods only serialized the data within the variant. They don't handle the variant's name.
https://github.com/cocoindex-io/cocoindex/blob/cf567ce8eb73053a8e539253ce125fb7f391f1ff/src/utils/yaml_ser.rs#L181-L191
https://github.com/cocoindex-io/cocoindex/blob/cf567ce8eb73053a8e539253ce125fb7f391f1ff/src/utils/yaml_ser.rs#L208-L216
This PR modifies them to store variant name when serialized, closes #443.

feat(yaml): store variant name in tuple and struct variants

---

src/utils/yaml_ser.rs

This PR adds unit tests for yaml serialization part, and resolves #439.
Each commit here is self-explanatory. The first commit removes the obsolete impls, since #444. The second commit adds a bunch of unit tests, achieving 99.12% coverage (calculated by cargo-tarpaulin).

test: add unit tests for yaml serializer

---

README.md

Adds the Image Search Example to README

Update README - Add Image Search Example

---

python/cocoindex/cli.py
python/cocoindex/flow.py
src/base/spec.rs
src/py/mod.rs

Following #427 and #404, this PR implements the flow spec pretty print in Rust and adds `--verbose` mode to enable more detailed output.
1. We first port the code from #404, using Rust, and then rewrite it using idiomatic Rust style, largely via `Display` trait.
2. We add verbose mode to the spec getter method.
1. We change it to use `get_spec` from Rust side.
2. We use `rich.Tree` instead of `rich.Console` for clearer readability.
`python main.py cocoindex show DocsToKG`
After adding `--verbose` flag, it will then produce a more detailed output with full operation specs, including all fields and JSON-like formatting, similar to preview in #404.
Resolves #410.

feat(pyo3): implement flow spec pretty print and add verbose mode

---

docs/docs/core/data_types.mdx
python/cocoindex/convert.py
python/cocoindex/tests/test_convert.py
python/cocoindex/typing.py

This PR tries to resolve #437.
`NamedTuples` support is added, so now struct types can be defined either by a dataclass or a namedtuple. A bunch of unit tests added for verifying the functionality and the docs is updated correpondingly.

feat: support namedtuple for struct types

---

src/execution/live_updater.rs
src/execution/source_indexer.rs
src/ops/interface.rs
src/ops/sources/amazon_s3.rs
src/ops/sources/google_drive.rs
src/ops/storages/neo4j.rs
src/utils/retriable.rs

feat(s3-push): delete(ack) event messages after processed

---

examples/amazon_s3_text_embedding/README.md
examples/amazon_s3_text_embedding/main.py
examples/amazon_s3_text_embedding/pyproject.toml
examples/amazon_s3_text_embedding/requirements.txt

chore(example): consolidate example for S3

---

examples/docs_to_knowledge_graph/.env
python/cocoindex/__init__.py
python/cocoindex/convert.py
python/cocoindex/flow.py
python/cocoindex/op.py
python/cocoindex/query.py
python/cocoindex/setting.py
src/builder/analyzed_flow.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/py/mod.rs

feat(transform-flow): support `eval()` for transient flow

---

python/cocoindex/__init__.py
python/cocoindex/flow.py
python/cocoindex/utils.py

feat(query-util): provide util functions to get default table name

---

docs/docs/core/data_types.mdx
python/cocoindex/typing.py
src/base/duration.rs
src/base/json_schema.rs
src/base/mod.rs
src/base/schema.rs
src/base/value.rs
src/execution/query.rs
src/ops/storages/neo4j.rs
src/ops/storages/postgres.rs
src/ops/storages/qdrant.rs
src/py/convert.rs

This is a continuation of the unmerged #368.
Resolves #344.

feat: add support for TimeDelta type in Python and Rust

---

python/cocoindex/cli.py

Closes #512.
Assuming we have defined two flows in the main.py.
Before this PR:
```
(cocoindex)$  uv run cocoindex show main.py
Usage: cocoindex show [OPTIONS] APP_FLOW_SPECIFIER
Try 'cocoindex show --help' for help.
Error: Multiple flows available, please specify which flow to target by appending :FlowName to the APP_TARGET.
Available: CodeEmbedding, TextEmbedding
```
After this PR (use up/down keys to navigate in the menu):
```
(cocoindex)$  uv run cocoindex show main.py
╭───────────────╮
│ Select a Flow │
╰───────────────╯
> CodeEmbedding
TextEmbedding
```

feat(cli): add interactive console navigation for multiple flow selections

---

pyproject.toml
python/cocoindex/auth_registry.py
python/cocoindex/cli.py
python/cocoindex/convert.py
python/cocoindex/flow.py
python/cocoindex/functions.py
python/cocoindex/lib.py
python/cocoindex/op.py
python/cocoindex/query.py
python/cocoindex/runtime.py
python/cocoindex/setting.py
python/cocoindex/setup.py
python/cocoindex/typing.py

 chore(mypy): make python codebase strictly typed

---

examples/fastapi_server_docker/requirements.txt

fix(examples): fastapi_docker_example requirements not including pg17 binaries for local running

---

docs/docs/ops/functions.md
examples/code_embedding/main.py
src/ops/functions/split_recursively.rs

Originated from #573, but this is a overall redesign of the `SplitRecursively` function.
- Allow users to specify a `min_chunk_size`
- Holistically planning the way of chunking to minimize "cost", considering the following factors
- AST structural level
- Literal styles (new lines, double new lines)
- Efficiency of overlap leverage
- Also for non-dividable elements (e.g. large comments, large strings), fallback to regexp based text chunking

feat(chunking): implement holistic chunking mechanism

---

Cargo.lock
Cargo.toml
src/ops/sources/google_drive.rs

Generate `EXPORT_MIME_TYPES` at compile time to avoid heap allocation during runtime.

perf(google_drive): generate `EXPORT_MIME_TYPES` at compile time

---

docs/docs/core/data_types.mdx
docs/docs/getting_started/quickstart.md
docs/docs/query.mdx
examples/text_embedding/Text_Embedding.ipynb
examples/text_embedding/main.py
examples/text_embedding/pyproject.toml
python/cocoindex/convert.py
python/cocoindex/functions.py
python/cocoindex/tests/test_convert.py
python/cocoindex/tests/test_typing.py
python/cocoindex/typing.py

Three main contents have been done in this PR:
1. We added the NDArray support as vector representations.
2. We added a few test suites for verifying this.
3. We updated the code examples and documentation accordingly.
Closed #525.

feat: add NumPy array support for vector representations

---

examples/code_embedding/pyproject.toml
examples/docs_to_knowledge_graph/pyproject.toml
examples/manuals_llm_extraction/pyproject.toml
examples/pdf_embedding/pyproject.toml
examples/product_recommendation/pyproject.toml
examples/text_embedding/pyproject.toml
examples/text_embedding_qdrant/pyproject.toml

Our project states Python 3.11+ is supported. This is also reflected in `pyproject.toml` and the installation section in our documentation.
However, some example projects set `requires-python = ">=3.10"` in `pyproject.toml`. This will cause issues when we use some management tools like `uv`, which considers this value when resolving dependencies.
Closes #612.

chore: update requires-python to >=3.11 in examples

---

Cargo.lock
Cargo.toml
python/cocoindex/convert.py
python/cocoindex/tests/test_convert.py
python/cocoindex/tests/test_typing.py
python/cocoindex/typing.py
src/py/convert.rs

Relates to #586. Should have been part of it.
This PR uses PyO3 NumPy bindings to handle NumPy array vector conversions.

feat: handle NumPy array vector in Python conversion

---

pyproject.toml
python/cocoindex/cli.py

In this PR, we added `watchfiles` for tracking file changes and then updated the `server` command to include reload options.
Closes #643.

feat(cli): add auto-reload for server command

---

pyproject.toml
python/cocoindex/functions.py

This PR fixes the CI failure.
1. The `numpy` dep is missing, after making `sentence-transformers` optional since #674. Because `sentence-transformers` pulled in numpy as one of its dependencies, our code used numpy implicitly.
2. The `mypy` type checks failed, cuz imports won't be found, after `sentence-transformers` is optional.

fix(ci): add numpy to dependencies and pass typing checks

---

python/cocoindex/cli.py
python/cocoindex/setup.py
src/builder/flow_builder.rs
src/execution/live_updater.rs
src/lib_context.rs
src/py/mod.rs
src/setup/db_metadata.rs
src/setup/driver.rs
src/setup/states.rs

feat(setup): provide internal logic for in-place setup

---

docs/docs/core/basics.md
docs/docs/core/flow_def.mdx
docs/docs/core/flow_methods.mdx
docs/docs/getting_started/quickstart.md
python/cocoindex/__init__.py
python/cocoindex/cli.py
python/cocoindex/flow.py
python/cocoindex/setup.py

feat(setup-api): update and officially expose setup API

---

python/cocoindex/flow.py
python/cocoindex/functions.py
python/cocoindex/op.py

This PR implements the suggested regime mentioned in #654.
Relates to #653, and closes #654.

feat: add `transform` method to `FlowBuilder`

---

examples/amazon_s3_embedding/README.md
examples/amazon_s3_embedding/main.py
examples/amazon_s3_embedding/pyproject.toml
examples/image_search/README.md
examples/image_search/main.py
examples/image_search/pyproject.toml

example: update examples to adopt setup API

---

docs/docs/ai/llm.mdx
python/cocoindex/llm.py
src/llm/mod.rs
src/llm/vllm.rs

Implements https://github.com/cocoindex-io/cocoindex/issues/659
Since vLLM doesn't support MacOS, models can only be run on CPU.
Choose a model with less than 1.5B Parameters and at least 2400 token support, for testing DeepSeek Coder 1.3B is used on MacOS M4
Install vLLM: (python < 3.13)
```bash
pip install vllm
```
Run vLLM Server
```bash
vllm serve deepseek-ai/deepseek-coder-1.3b-instruct
```
```python
cocoindex.LlmSpec(
api_type=cocoindex.LlmApiType.VLLM,
model="deepseek-ai/deepseek-coder-1.3b-instruct",
address="http://127.0.0.1:8000/v1",                    # /v1 is mandatory 
)
```
Also vLLM Supports Embedding the same way as OpenAI, a new PR for it would be better - https://docs.vllm.ai/en/v0.6.6/serving/openai_compatible_server.html#embeddings-api
More info - …

feat(llm): Add vLLM Support

---

python/cocoindex/flow.py
src/base/spec.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/builder/plan.rs
src/execution/source_indexer.rs
src/utils/concur_control.rs
src/utils/mod.rs

feat(flow-control): basic flow control for source #rows

---

docs/docs/core/flow_def.mdx
python/cocoindex/flow.py
src/base/spec.rs
src/base/value.rs
src/builder/analyzer.rs
src/builder/flow_builder.rs
src/builder/plan.rs
src/execution/evaluator.rs

feat(flow-control): support flow control for "for each" operations

---

docs/docs/core/flow_def.mdx
docs/docs/core/flow_methods.mdx
python/cocoindex/__init__.py
python/cocoindex/flow.py
src/lib_context.rs
src/py/mod.rs

feat(remove): add a remove_flow() method

---

src/ops/functions/embed_text.rs
src/ops/functions/extract_by_llm.rs
src/ops/functions/mod.rs
src/ops/functions/parse_json.rs
src/ops/functions/split_recursively.rs
src/ops/functions/test_utils.rs

feat(rs): add utilities to streamline tests for flow functions

---

python/cocoindex/convert.py
python/cocoindex/tests/test_convert.py
python/cocoindex/typing.py

feat(convert): enhance dict and struct encoding with type awareness

---

src/llm/gemini.rs
src/llm/mod.rs
src/ops/functions/embed_text.rs

feat(vertex): support Vertex AI for embedding

---

Cargo.lock
Cargo.toml
README.md
examples/azure_blob_embedding/.env.example
examples/azure_blob_embedding/README.md
examples/azure_blob_embedding/main.py
examples/azure_blob_embedding/pyproject.toml
python/cocoindex/sources.py
src/ops/registration.rs
src/ops/sources/azure_blob.rs
src/ops/sources/mod.rs

- Implement Azure Blob Storage source following S3 pattern
- Support multiple authentication methods with priority:
* Connection string (highest priority)
* SAS token (with proper permissions validation)
* Account key (full access)
* Anonymous access (public containers)
- Include file pattern filtering (include/exclude glob patterns)

add Azure Blob Storage source with full authentication support

---

src/llm/mod.rs
src/llm/ollama.rs

 feat(embed-text): add `EmbedText` for Ollama

---

docs/docs/core/live_updates.md
docs/docs/tutorials/live_updates.md
docs/sidebars.ts
examples/live_updates/.env
examples/live_updates/README.md
examples/live_updates/data/bizarre_animals.md
examples/live_updates/data/chunk_norris.md
examples/live_updates/main.py
examples/live_updates/pyproject.toml

Relates #716.
- created a complete example project to illustrate the usage of live updates
- added the documentation to walk through the functionalities of the live updates

example: add the tutorial of performing live updates

---

python/cocoindex/convert.py
python/cocoindex/flow.py
python/cocoindex/op.py
python/cocoindex/tests/test_convert.py

This is for better composability.
We also cleaned up related logic and drop unnecessary support for cases that engine fields don't match engine type - which should not happen. This simplifies code and tests.

refactor: `make_engine_value_decoder()` takes `AnalyzedTakesInfo`

---

.github/workflows/_test.yml
pyproject.toml
python/cocoindex/tests/test_transform_flow.py

test: add unit tests to execute transform flow e2e

---

examples/amazon_s3_embedding/.env.example
examples/azure_blob_embedding/.env.example
examples/code_embedding/.env
examples/face_recognition/.env
examples/fastapi_server_docker/.env
examples/gdrive_text_embedding/.env.example
examples/image_search/.env
examples/manuals_llm_extraction/.env
examples/multi_format_indexing/.env
examples/paper_metadata/.env.example
examples/pdf_embedding/.env
examples/text_embedding/.env
examples/text_embedding_qdrant/.env

chore: set `PYTORCH_ENABLE_MPS_FALLBACK=1` for examples using GPU

---

python/cocoindex/cli.py
python/cocoindex/functions.py
python/cocoindex/op.py
python/cocoindex/subprocess_exec.py
python/cocoindex/tests/test_transform_flow.py
python/cocoindex/user_app_loader.py

feat(subprocessing): implement subprocessing for GPU workloads

---

docs/docs/ops/targets.md
src/ops/targets/postgres.rs
src/utils/mod.rs
src/utils/str_sanitize.rs

feat: strip U+0000 in writing to Postgres to overcome its limitation

---

python/cocoindex/flow.py
python/cocoindex/query_handler.py
src/lib_context.rs
src/py/mod.rs
src/service/flows.rs
src/service/query_handler.rs

feat(query-handler): minor adjustment for the API

---

python/cocoindex/convert.py
python/cocoindex/flow.py
python/cocoindex/op.py
python/cocoindex/tests/test_convert.py
python/cocoindex/typing.py

feat: add strong-typed representation of cocoindex type in Python

---

README.md
examples/text_embedding_lancedb/.env
examples/text_embedding_lancedb/.gitignore
examples/text_embedding_lancedb/README.md
examples/text_embedding_lancedb/main.py
examples/text_embedding_lancedb/markdown_files/rfc8259.md
examples/text_embedding_lancedb/pyproject.toml

example(lancedb): add lancedb target example

---

python/cocoindex/functions.py
src/ops/functions/mod.rs
src/ops/functions/split_by_separators.rs
src/ops/registration.rs
src/ops/shared/mod.rs
src/ops/shared/split.rs

Adds `SplitBySeparators` (regex-only, no chunk-size planning).
Rust executor + registration; Python spec; schema matches `SplitRecursively`.
143 passed / 1 skipped (DB). Closes #1003. cc @georgeh0

feat(ops): SplitBySeparators — regex-only splitter (Rust+Py)

---

python/cocoindex/__init__.py
src/lib_context.rs
src/py/mod.rs

fix: make sure pyo3 runtime is initialized before all others

---

python/cocoindex/functions/__init__.py
python/cocoindex/functions/_engine_builtin_specs.py
python/cocoindex/functions/colpali.py
python/cocoindex/functions/sbert.py

Refactored module functions to subpackage in python sdk.
Closes Issue: #1080 
Ran precommit hooks (all passed)
Ran tests to see if import works (works).

reafactored functions module in python sdk to subpackage

---

.pre-commit-config.yaml
dev/README.md
dev/generate_cli_docs.py
docs/docs/core/cli-commands.md
docs/docs/core/cli-reference.md
docs/docs/core/cli.mdx

Generate full CLI docs from click's metadata and also added it in pre commit hooks
Ran precommit hooks.
Added one Readme for clearance what /(dev contains if not needed will remove it pls tell me)
docs will be generated at docs/docs/core/cli-reference.md also added it in pre  commit hooks (can check in image, name: generate-cli-docs)

generate full CLI docs from click's metadata and also added it in precommit hooks

---

python/cocoindex/cli.py

Adds '--reset' flag to 'setup', 'update', and 'server' cli commands to automatically drop existing setup before running the command.
Closes #778

feat: add --reset flag for setup, update, and server commands

---

src/builder/analyzer.rs
src/builder/plan.rs
src/execution/evaluator.rs
src/execution/live_updater.rs
src/execution/row_indexer.rs
src/execution/source_indexer.rs
src/execution/stats.rs

can now collect additional counter for number of rows that are being processed - for stats
Written 7 tests status

feat: collect additional counter for number of rows that are being processed for stats

---

python/cocoindex/auth_registry.py
python/cocoindex/engine_object.py
python/cocoindex/engine_value.py
python/cocoindex/flow.py
python/cocoindex/lib.py
python/cocoindex/op.py
python/cocoindex/tests/test_engine_object.py
python/cocoindex/tests/test_engine_value.py

split convert.py into 2 modules engine_object and engine_value , also split current tests into two test files test_engine_object and test_engine_value.

feat: split convert.py into 2 modules engine_object and engine_value along with splitting of tests

---

python/cocoindex/flow.py
python/cocoindex/targets/_engine_builtin_specs.py
src/ops/factory_bases.rs
src/ops/interface.rs
src/ops/registration.rs
src/ops/targets/postgres.rs
src/setup/driver.rs
src/setup/states.rs

feat(postgres-sql-attachments): add `PostgresSqlAttachment`

---

src/execution/db_tracking_setup.rs
src/setup/db_metadata.rs
src/setup/driver.rs
src/setup/states.rs

feat(attachment): update tracked states even if no update action needed

---

src/ops/functions/split_recursively.rs

Resolves #898
The previous implementation of `SplitRecursively` used a recursive approach to traverse the AST. This caused a **stack overflow crash** when processing code with deeply nested structures, as noted in the issue. The temporary recursion limit was a stopgap that negatively affected the quality of the splits.
This PR refactors the core logic in `collect_atom_chunks` to be **fully iterative**.
- The recursive calls have been replaced with an explicit stack on the heap (`Vec<Box<dyn Iterator>>`).
- This completely removes the risk of a stack overflow, regardless of AST depth, and allows us to remove the old recursion limit.
All tests now pass successfully with `cargo test`. The changes have been verified against deeply nested code structures that previously caused the application …

Fix: Flatten recursion in SplitRecursively to prevent stack overflow

---

examples/text_embedding/main.py
python/cocoindex/targets/_engine_builtin_specs.py
src/ops/targets/postgres.rs

chore(postgres-sql-cmd): rename

---

Cargo.lock
Cargo.toml
src/execution/live_updater.rs
src/llm/gemini.rs
src/utils/retryable.rs

fix(vertexai-retry): retry properly for Vertex AI

---

src/execution/live_updater.rs

fix: log instead of error out on live mode source-level error

---

docs/docs/ops/functions.md
examples/code_embedding/main.py
python/cocoindex/functions/__init__.py
python/cocoindex/functions/_engine_builtin_specs.py
src/ops/functions/detect_program_lang.rs
src/ops/functions/mod.rs
src/ops/registration.rs
src/ops/shared/program_langs.rs

feat: add `DetectProgrammingLanguage` function
